# Generated by Django 4.1.3 on 2024-04-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='medicines',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicine_name', models.CharField(max_length=50)),
                ('medicine_genre', models.CharField(max_length=50)),
                ('medicine_text', models.TextField()),
                ('medicine_image_url', models.CharField(max_length=500)),
                ('medicine_buy_link', models.CharField(max_length=500)),
            ],
        ),
    ]
