# Generated by Django 4.1.3 on 2024-04-29 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_core', '0002_images'),
    ]

    operations = [
        migrations.DeleteModel(
            name='images',
        ),
    ]
